services:
    _defaults:
        public: true

    # If you need to access services in a testController, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with testController. For example:
    #
    # testController.App\Service\MyService: '@App\Service\MyService'
